
/**************************************************************
 *	
 *	BlockDownSFX, 8 bit, 11025Hz,
 *	1 channel, 2592 bytes/channel
 *	Total Size: 1 * 2592 + 4 (header) = 2636 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/katiecarlson/CS2261/GBA-Final-Project/BlockDownSFX.wav
 *	Time-stamp: Mon Nov 25 09:37:09 2019
 *	
 **************************************************************/

#ifndef __BLOCKDOWNSFXH__
#define __BLOCKDOWNSFXH__

#define BLOCKDOWNSFXFREQ 11025
#define BLOCKDOWNSFXLEN 2592

extern const unsigned char BlockDownSFX[2592];

#endif /* __BLOCKDOWNSFXH__ */
