
/**************************************************************
 *	
 *	BlockUpSFX, 8 bit, 11025Hz,
 *	1 channel, 7488 bytes/channel
 *	Total Size: 1 * 7488 + 4 (header) = 7532 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/katiecarlson/CS2261/GBA-Final-Project/BlockUpSFX.wav
 *	Time-stamp: Mon Nov 25 09:37:26 2019
 *	
 **************************************************************/

#ifndef __BLOCKUPSFXH__
#define __BLOCKUPSFXH__

#define BLOCKUPSFXFREQ 11025
#define BLOCKUPSFXLEN 7488

extern const unsigned char BlockUpSFX[7488];

#endif /* __BLOCKUPSFXH__ */
