
/**************************************************************
 *	
 *	BlockTurnSFX, 8 bit, 11025Hz,
 *	1 channel, 6336 bytes/channel
 *	Total Size: 1 * 6336 + 4 (header) = 6380 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/katiecarlson/CS2261/GBA-Final-Project/BlockTurnSFX.wav
 *	Time-stamp: Mon Nov 25 17:32:10 2019
 *	
 **************************************************************/

#ifndef __BLOCKTURNSFXH__
#define __BLOCKTURNSFXH__

#define BLOCKTURNSFXFREQ 11025
#define BLOCKTURNSFXLEN 6336

extern const unsigned char BlockTurnSFX[6336];

#endif /* __BLOCKTURNSFXH__ */
