
/**************************************************************
 *	
 *	CheatChime, 8 bit, 11025Hz,
 *	1 channel, 16363 bytes/channel
 *	Total Size: 1 * 16363 + 4 (header) = 16407 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/katiecarlson/CS2261/GBA-Final-Project/Audio/CheatChime.wav
 *	Time-stamp: Fri Dec 06 13:33:16 2019
 *	
 **************************************************************/

#ifndef __CHEATCHIMEH__
#define __CHEATCHIMEH__

#define CHEATCHIMEFREQ 11025
#define CHEATCHIMELEN 16363

extern const unsigned char CheatChime[16363];

#endif /* __CHEATCHIMEH__ */
