
/**************************************************************
 *	
 *	DubstepGameTheme, 8 bit, 11025Hz,
 *	1 channel, 1719648 bytes/channel
 *	Total Size: 1 * 1719648 + 4 (header) = 1719692 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/katiecarlson/CS2261/GBA-Final-Project/Audio/DubstepGameTheme.wav
 *	Time-stamp: Fri Dec 06 13:33:24 2019
 *	
 **************************************************************/

#ifndef __DUBSTEPGAMETHEMEH__
#define __DUBSTEPGAMETHEMEH__

#define DUBSTEPGAMETHEMEFREQ 11025
#define DUBSTEPGAMETHEMELEN 1719648

extern const unsigned char DubstepGameTheme[1719648];

#endif /* __DUBSTEPGAMETHEMEH__ */
