
/**************************************************************
 *	
 *	MainGameTheme, 8 bit, 11025Hz,
 *	1 channel, 1641600 bytes/channel
 *	Total Size: 1 * 1641600 + 4 (header) = 1641644 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/katiecarlson/CS2261/GBA-Final-Project/MainGameTheme.wav
 *	Time-stamp: Mon Nov 25 09:36:53 2019
 *	
 **************************************************************/

#ifndef __MAINGAMETHEMEH__
#define __MAINGAMETHEMEH__

#define MAINGAMETHEMEFREQ 11025
#define MAINGAMETHEMELEN 1641600 - 600

extern const unsigned char MainGameTheme[1641600];

#endif /* __MAINGAMETHEMEH__ */
