
/**************************************************************
 *	
 *	MainGameTheme, 8 bit, 11025Hz,
 *	1 channel, 1410560 bytes/channel
 *	Total Size: 1 * 1410560 + 4 (header) = 1410604 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/katiecarlson/CS2261/GBA-Final-Project/Audio/MainGameTheme.wav
 *	Time-stamp: Fri Dec 06 13:33:36 2019
 *	
 **************************************************************/

#ifndef __MAINGAMETHEMEH__
#define __MAINGAMETHEMEH__

#define MAINGAMETHEMEFREQ 11025
#define MAINGAMETHEMELEN 1410560

extern const unsigned char MainGameTheme[1410560];

#endif /* __MAINGAMETHEMEH__ */
