
/**************************************************************
 *	
 *	PuzzleDoneChime, 8 bit, 11025Hz,
 *	1 channel, 59470 bytes/channel
 *	Total Size: 1 * 59470 + 4 (header) = 59514 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/katiecarlson/CS2261/GBA-Final-Project/Audio/PuzzleDoneChime.wav
 *	Time-stamp: Fri Dec 06 13:33:46 2019
 *	
 **************************************************************/

#ifndef __PUZZLEDONECHIMEH__
#define __PUZZLEDONECHIMEH__

#define PUZZLEDONECHIMEFREQ 11025
#define PUZZLEDONECHIMELEN 59470

extern const unsigned char PuzzleDoneChime[59470];

#endif /* __PUZZLEDONECHIMEH__ */
