
/**************************************************************
 *	
 *	StartTheme, 8 bit, 11025Hz,
 *	1 channel, 1232896 bytes/channel
 *	Total Size: 1 * 1232896 + 4 (header) = 1232940 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/katiecarlson/CS2261/GBA-Final-Project/Audio/StartTheme.wav
 *	Time-stamp: Fri Dec 06 13:33:58 2019
 *	
 **************************************************************/

#ifndef __STARTTHEMEH__
#define __STARTTHEMEH__

#define STARTTHEMEFREQ 11025
#define STARTTHEMELEN 1232896

extern const unsigned char StartTheme[1232896];

#endif /* __STARTTHEMEH__ */
