
/**************************************************************
 *	
 *	StartTheme, 8 bit, 11025Hz,
 *	1 channel, 1976556 bytes/channel
 *	Total Size: 1 * 1976556 + 4 (header) = 1976600 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/katiecarlson/CS2261/GBA-Final-Project/Audio/StartTheme.wav
 *	Time-stamp: Sun Dec 08 20:57:50 2019
 *	
 **************************************************************/

#ifndef __STARTTHEMEH__
#define __STARTTHEMEH__

#define STARTTHEMEFREQ 11025
#define STARTTHEMELEN 1976556 - 400

extern const unsigned char StartTheme[1976556];

#endif /* __STARTTHEMEH__ */
