
/**************************************************************
 *	
 *	WindEffect, 8 bit, 11025Hz,
 *	1 channel, 22655 bytes/channel
 *	Total Size: 1 * 22655 + 4 (header) = 22699 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/katiecarlson/CS2261/GBA-Final-Project/Audio/WindEffect.wav
 *	Time-stamp: Fri Dec 06 13:34:08 2019
 *	
 **************************************************************/

#ifndef __WINDEFFECTH__
#define __WINDEFFECTH__

#define WINDEFFECTFREQ 11025
#define WINDEFFECTLEN 22655

extern const unsigned char WindEffect[22655];

#endif /* __WINDEFFECTH__ */
